name: Build_hhblog
on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 #检出代码仓库中的代码

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - run: go version

      - name: Build
        run: |
          ls
          ls gvb_server

#      - name: Test
#        run: go test -v ./...

      - name: Archive build artifacts (optional)
        if: always() # 无论构建成功与否都执行此步骤
        uses: actions/upload-artifact@v3
        with:
          name: application-binary
          path: ./hhblog # 替换为实际的可执行文件路径
